version: "3.8"
services:
  backend:
    container_name: backend-container
    #image: "efrei2023/backend:1"
    build:
      context: backend
      dockerfile: Dockerfile
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    networks:
      - efrei_net

  frontend:
    container_name: frontend-container
    build:
      context: frontend
      dockerfile: Dockerfile
    #image: "efrei2023/frontend:1"
    networks:
      - efrei_net
    ports:
      - "8089:80"
    depends_on:
      - backend

networks:
  efrei_net:
    driver: bridge
