version: "3.8"

services:
  jenkins:
    image: jenkins/jenkins:lts-jdk17
    container_name: adoring_johnson
    ports:
      - "8080:8080"
      - "50000:50000"
    restart: on-failure
    networks:
      - jenkins
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

networks:
  jenkins:
    external: true
