apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: efrei2023/frontend:1
          ports:
            - containerPort: 80
          env:
            - name: SQLALCHEMY_DATABASE_URI
              value: "postgresql://postgres:postgres@backend:5432/postgres"
